export const SET_IS_FETCHING_CITY_DATA_TRUE = '[APP] SET_IS_FETCHING_CITY_DATA_TRUE';

export const SET_IS_FETCHING_CITY_DATA_FALSE = '[APP] SET_IS_FETCHING_CITY_DATA_FALSE';

export const SET_CURRENT_CITY_WEATHER_DATA = '[APP] SET_CURRENT_CITY_WEATHER_DATA';
